spring:
  application:
    name: interview
  profiles:
    active: local
  docker:
    compose:
      enabled: true

server:
  port: 8080

app:
  auth:
    max-send-count: 5
    min-send-count: 0
    verification-expiration-minutes: 10
    count-reset-hours: 24
  email:
    base-url: ${EMAIL_BASE_URL:http://localhost:8080}
    sender-email: ${EMAIL_SENDER:noreply@personal-interview.com}
    sender-name: Personal Interview
  jwt:
    secret-key: ${JWT_SECRET_KEY:myDefaultSecretKeyForDevelopmentPurposeOnly12345678901234567890}
    access-expiration-ms: 1800000  # 30분
    refresh-expiration-ms: 604800000  # 7일
